spring.application.name=api-gateway
server.port=8080

user.service.url=${USER_SERVICE_URL:http://localhost:8081}
menu.service.url=${MENU_SERVICE_URL:http://localhost:8082}
order.service.url=${ORDER_SERVICE_URL:http://localhost:8083}