spring.application.name=menu-microservice
server.port=8082

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/menu_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:menu_svc}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:menu_pass}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

user.service.url=${USER_SERVICE_URL:http://localhost:8081}

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
jwt.secret=${JWT_SECRET:anything-at-least-32-characters-long}
