spring.application.name=order-microservice
server.port=8083

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5434/order_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:order_svc}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:order_pass}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

user.service.url=${USER_SERVICE_URL:http://localhost:8081}
menu.service.url=${MENU_SERVICE_URL:http://localhost:8082}